<a href="https://colab.research.google.com/github/pritamsingh7631-ui/hangman-game/blob/main/numphy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# first list
list1 = [10, 20, 30, 40, 50]

# second list
list2 = [1, "apple", 3.5, True, "hello"]

# combine lists
combined_list = list1 + list2

# print result
print(combined_list)

[10, 20, 30, 40, 50, 1, 'apple', 3.5, True, 'hello']


In [2]:
import numpy as np

# Creating a 2D array
s = [[1, 2, 3],
     [3, 4, 5],
     [5, 6, 7]]

S1 = np.array(s)

print("Original Array:")
print(S1)

# Indexing
print("\nFirst Row:")
print(S1[0])

print("\nSecond Row:")
print(S1[1])

print("\nLast Row:")
print(S1[-1])

# Accessing elements
print("\nElement at row 0 column 0:")
print(S1[0][0])

print("\nElement at row 1 column 2:")
print(S1[1][2])

# Updating value
S1[0][0] = 12

print("\nUpdated Array:")
print(S1)

# Array addition
S2 = S1 + S1

print("\nAddition of Arrays:")
print(S2)

# 1D array
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("\n1D Array:")
print(v)

# Adding number
print("\nAdd 5:")
print(v + 5)

print("\nAdd 2:")
print(v + 2)

# Slicing
print("\nFirst 5 elements:")
print(v[:5])

# Reverse array
print("\nReverse Array:")
print(v[::-1])

Original Array:
[[1 2 3]
 [3 4 5]
 [5 6 7]]

First Row:
[1 2 3]

Second Row:
[3 4 5]

Last Row:
[5 6 7]

Element at row 0 column 0:
1

Element at row 1 column 2:
5

Updated Array:
[[12  2  3]
 [ 3  4  5]
 [ 5  6  7]]

Addition of Arrays:
[[24  4  6]
 [ 6  8 10]
 [10 12 14]]

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Add 5:
[ 6  7  8  9 10 11 12 13 14 15]

Add 2:
[ 3  4  5  6  7  8  9 10 11 12]

First 5 elements:
[1 2 3 4 5]

Reverse Array:
[10  9  8  7  6  5  4  3  2  1]
